FROM python:3.10.13-slim-bookworm

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y git

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --upgrade wheel

COPY requirements_dev.txt /tmp/requirements.txt
WORKDIR /tmp
RUN pip install --no-cache-dir -r requirements.txt
RUN rm requirements.txt
